# Generated by Django 5.1.2 on 2025-03-19 14:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Building',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building_floor_count', models.IntegerField()),
                ('building_height', models.FloatField()),
                ('building_age', models.IntegerField()),
                ('building_plinth_area', models.IntegerField()),
                ('earthquake_magnitude', models.FloatField()),
                ('foundation_type', models.CharField(choices=[('Other', 'Other'), ('Mud mortar-Stone/Brick', 'Mud mortar-Stone/Brick'), ('Cement-Stone/Brick', 'Cement-Stone/Brick'), ('Bamboo/Timber', 'Bamboo/Timber'), ('RC', 'RC')], max_length=25)),
                ('roof_type', models.CharField(choices=[('Bamboo/Timber-Light roof', 'Bamboo/Timber-Light roof'), ('Bamboo/Timber-Heavy roof', 'Bamboo/Timber-Heavy roof'), ('RCC/RB/RBC', 'RCC/RB/RBC')], max_length=25)),
                ('land_surface_condition', models.CharField(choices=[('Moderate slope', 'Moderate slope'), ('Flat', 'Flat'), ('Steep slope', 'Steep slope')], max_length=25)),
                ('ground_floor_type', models.CharField(choices=[('Mud', 'Mud'), ('RC', 'RC'), ('Brick/Stone', 'Brick/Stone'), ('Timber', 'Timber'), ('Other', 'Other')], max_length=25)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='BuildingFullData',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('building_floor_count_pre_eq', models.IntegerField()),
                ('building_floor_count_post_eq', models.IntegerField()),
                ('building_height_pre_eq', models.FloatField()),
                ('building_height_post_eq', models.FloatField()),
                ('building_age', models.IntegerField()),
                ('building_plinth_area', models.IntegerField()),
                ('earthquake_magnitude', models.FloatField()),
                ('foundation_type', models.CharField(choices=[('Other', 'Other'), ('Mud mortar-Stone/Brick', 'Mud mortar-Stone/Brick'), ('Cement-Stone/Brick', 'Cement-Stone/Brick'), ('Bamboo/Timber', 'Bamboo/Timber'), ('RC', 'RC')], max_length=25)),
                ('roof_type', models.CharField(choices=[('Bamboo/Timber-Light roof', 'Bamboo/Timber-Light roof'), ('Bamboo/Timber-Heavy roof', 'Bamboo/Timber-Heavy roof'), ('RCC/RB/RBC', 'RCC/RB/RBC')], max_length=25)),
                ('land_surface_condition', models.CharField(choices=[('Moderate slope', 'Moderate slope'), ('Flat', 'Flat'), ('Steep slope', 'Steep slope')], max_length=25)),
                ('ground_floor_type', models.CharField(choices=[('Mud', 'Mud'), ('RC', 'RC'), ('Brick/Stone', 'Brick/Stone'), ('Timber', 'Timber'), ('Other', 'Other')], max_length=25)),
                ('date_added', models.DateTimeField(auto_now_add=True)),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
