# Generated by Django 5.2.1 on 2025-05-17 19:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('api', '0002_building_prediction'),
    ]

    operations = [
        migrations.AddField(
            model_name='buildingfulldata',
            name='felt_damage',
            field=models.FloatField(default=1),
            preserve_default=False,
        ),
    ]
